### PR TITLE
prepare for brimdata/zed#2632

### PR DESCRIPTION
**Pull request by nwt**
brimdata/zed#2632 removes the `pcap` command and `zqd listen`'s `-suricatarunner`, `-suricataupdater`, and `-zeekrunner` flags.

### CODE REVIEW

**Review by mason-fish — APPROVED** [review]
lgtm

**Comment by mattnibs** [comment]
I'd prefer to merge these changes into #1589, the rebases are making this pr more difficult then it already is.

**Comment by nwt** [comment]
@mattnibs: That's fine with me. I'm going to keep this open while I look into a CI failure but will plan to close without merging.

**Comment by nwt** [comment]
@mattnibs and I agreed that it makes sense to merge this so we we can merge brimdata/zed#2632 without breaking Brim CI.

**Pull request merged**
