### PR TITLE
Zui Welcome Page

### LINKED ISSUE #2387: Create a simple welcome page
This would be a page to greet new users on first ever Zui launch in lieu of some of the existing pages such as Release Notes or Import Files. It would include app links and web links for common tasks.

Strictly speaking we may not need this for Zui v1.0 since we've been thinking the top priority is to GA Zui when we have feature parity with the prior Brim app. However, it'd very much be a nice-to-have, so it's in our v1.0 goals for now.

### PR DESCRIPTION
**Pull request by jameskerr**
Fixes #2387

On first ever startup, this page will appear. Then it will always be available from the "Help" app menu.

image

https://user-images.githubusercontent.com/3460638/188247241-2975a453-43bb-428c-8e88-2296c6585c24.mp4

### CODE REVIEW

**Comment by philrz** [comment]
@kerr: I just tried testing the "first ever startup" experience at commit 4fc6c27 on this branch. As shown in the attached video, when I clicked "Import Data", it opened another"New Pool" tab rather than navigating to the initial one I'm accustomed to seeing on a freshly launched app. It's pretty harmless, but is it something you'd want to look into before we merge this?

https://user-images.githubusercontent.com/5934157/188247802-e0a0427b-a723-4eb7-b017-b6e053253da1.mp4

**Comment by jameskerr** [comment]
@philrz yeah, I'll fix that duplicate new pool page.

**Comment by jameskerr** [comment]
Actually, that was already fixed in the latest push.

**Review by philrz — APPROVED** [review]
Cool. I've confirmed on the branch that the "duplicate new pool page" issue appears fixed and everything else is looking good, so that's a functional 👍  from me.

**Pull request merged**
