### PR TITLE
Increase toast loading duration to biggest number

### LINKED ISSUE #2497: Export continues long after "Exporting..." pop-up goes away (regression)
Repro is with Brim commit 9912a29. An issue with the exact same symptom was found once before in #1346 and ultimately fixed via #1424, so this represents a regression. Perhaps info from the prior fix will help quickly narrow down and fix this one also.

The attached video shows the initiation of a large ZNG export. After the "Exporting..." pop-up fades away, you can see the ZNG file continues to increase in size, indicating the export operation is still in-progress. As a user, a pop-up that communicates an in-progress operation (e.g. a verb ending in "ing"), my assumption is that when the pop-up goes away, the operation described has completed.

https://user-images.githubusercontent.com/5934157/186023455-bf4773a0-8c2d-412c-ac1a-9507926fb3b1.mp4

### PR DESCRIPTION
**Pull request by jameskerr**
Fixes #2497

I tested this by exporting 3.4 gigs of ndjson. The export took over a minute, did not disappear, and then displayed the "export complete" 
message.

### CODE REVIEW

**Comment by philrz** [comment]
@jameskerr: Because the repro involves large data sets and a long delay, am I guessing this one is too hairy to add a test for? I ask because we've regressed in this area after fixing it once before, so my usual instincts are to plead for a test so this doesn't keep happening. 🙁

**Comment by jameskerr** [comment]
I know, I was trying to think of how to test this. I think there is something I can do. I'll add.

**Comment by jameskerr** [comment]
I also added the file name to the export message:

image


In the future it would be sweet to add a little link to open the containing folder in the default file explorer.

**Comment by philrz** [comment]
Oooo! I like the file name in the export message. It's orthogonal so not asking for this now, but it reminds me of the Import pop-up that could use similar detail per #1345.

**Review by philrz — APPROVED** [review]
My test on this branch was a successful, so that's a functional 👍 from me!

Also, I've added a checkbox to #1493 as a reminder that we may one day want to revisit this area to add more testing.

**Comment by jameskerr** [comment]
Yup, that was on my mind so I added it here too. Alright!

**Pull request merged**
